```python
>>> round(calc_nominaldiameter(0.501), 4)
Traceback (most recent call last):
Exception: Invalid averagepipediameter value of 0.501
```
[stackoverflow.com ~ Can you check that an exception is thrown with doctest in Python?](https://stackoverflow.com/a/12609)
